### ISSUE TITLE
Codepen Examples/GitHub Pages

### ISSUE THREAD

**Issue by guivr** [guivr/Chameleon#3]

**Comment by jeffersondanielss** [comment]
Já tem algo em mente para a GH page?

**Comment by guivr** [comment]
@jeffersondanielss: Pensei em fazer algo bem simples que rodasse o Chameleon mudando a cor e outras propriedades realtime, com um botao pra ver uma collection no Codepen com exemplos. O que acha?

**Comment by jeffersondanielss** [comment]
Pensei em algo assim também, ia ser legal se tivesse o Chamaleon mudando a cor do logo, você tem ele em SVG?

**Comment by jeffersondanielss** [comment]
Como o branch **gh-pages** não existe não consegui fazer o pull resquest, mas fiz um commit ai com o que tinha em mente :+1:

**Comment by guivr** [comment]
@jeffersondanielss Curti muiito!! Ja ta rodando, irmao! Valeu pela contribuicao, seja bem-vindo aos contribuidores haha :)

**Comment by jeffersondanielss** [comment]
@guivr massa!! Obg, precisar estamos ai :)
